### ISSUE TITLE
Can I set up via singularity?

### ISSUE THREAD

**Issue by evayfang2019** [PacificBiosciences/wdl-dockerfiles#35]
Dear developers,
For some reason, I don't have Docker installed on my server. Can these images be pulled through singularity? And how to set up?
Thanks!

**Comment by williamrowell** [comment]
Hello,

If you're trying to use these images in the context of the WDL workflows, it's best to use a WDL runner configuration that uses singularity to pull the images, for example:

- https://miniwdl.readthedocs.io/en/latest/runner_backends.html#singularity-beta
- https://github.com/miniwdl-ext/miniwdl-slurm
- https://cromwell.readthedocs.io/en/stable/tutorials/Containers/#configuring-cromwell-for-singularity

If trying to use these images directly, you can create a singularity `.sif` file by pulling from our default container repository, [Quay.io](https://quay.io/organization/pacbio), e.g.:

```bash
singularity pull docker://quay.io/pacbio/pbsv:2.9.0_1.14_build1
```
