### ISSUE TITLE
Error when pulling docker images

### ISSUE THREAD

**Issue by letunglam1991** [PacificBiosciences/wdl-dockerfiles#36]
When i pull docker images by cmd: **./util/build_docker_images -d docker -p -c pacbio**. I get that error. Can you help me fix this.

_[2023-11-01T09:52:18+0700] Pushing pacbio/picard-bedtointervallist:v1.10.0_build2
The push refers to repository [docker.io/pacbio/picard-bedtointervallist]
dcdfd1232b72: Preparing
d4ca87cd64e9: Preparing
1438ab96bbed: Preparing
fa38fbb199f9: Preparing
ab2731ec3f53: Preparing
6fa1f4185aa2: Waiting
ad6562704f37: Waiting
denied: requested access to the resource is denied_

**Comment by williamrowell** [comment]
Hello,

Before we dig in too deep, can I ask your goal?

Are you trying to:
- run a workflow using miniwdl/cromwell?
- build and deploy these images to your own container repo?
- use the tools in an image _outside_ of the context of a workflow?

In most use cases, it's not necessary to build the images yourself, and you can use the pre-built images we've deployed to [quay.io](https://quay.io/organization/pacbio).

Please reach out to PacBio Field Support or Tech Support if you're looking into how to run the workflows.

The [command](https://github.com/PacificBiosciences/wdl-dockerfiles#build-and-push-all-images-in-the-docker-directory-using-the-pacbio-container-registry) you've posted, `./util/build_docker_images -d docker -p -c {some_repo}`, is intended to build and *push* images to a repo, not to pull the images from the repo.

If you're using these images within the context of the WDL workflows, the WDL runner (miniwdl or Cromwell) needs to be configured to pull and cache these images.

To pull a single image outside of the context of a WDL runner like miniwdl or Cromwell, you could use something like the commands below:

```bash
# for docker
docker pull quay.io/pacbio/bcftools:1.14_build2

# for singularity
singularity pull docker://quay.io/pacbio/bcftools:1.14_build2
```

**Comment by letunglam1991** [comment]
> Hello,
> 
> Before we dig in too deep, can I ask your goal?
> 
> Are you trying to:
> 
> * run a workflow using miniwdl/cromwell?
> * build and deploy these images to your own container repo?
> * use the tools in an image _outside_ of the context of a workflow?
> 
> In most use cases, it's not necessary to build the images yourself, and you can use the pre-built images we've deployed to [quay.io](https://quay.io/organization/pacbio).
> 
> Please reach out to PacBio Field Support or Tech Support if you're looking into how to run the workflows.
> 
> The [command](https://github.com/PacificBiosciences/wdl-dockerfiles#build-and-push-all-images-in-the-docker-directory-using-the-pacbio-container-registry) you've posted, `./util/build_docker_images -d docker -p -c {some_repo}`, is intended to build and _push_ images to a repo, not to pull the images from the repo.
> 
> If you're using these images within the context of the WDL workflows, the WDL runner (miniwdl or Cromwell) needs to be configured to pull and cache these images.
> 
> To pull a single image outside of the context of a WDL runner like miniwdl or Cromwell, you could use something like the commands below:
> 
> ```shell
> # for docker
> docker pull quay.io/pacbio/bcftools:1.14_build2
> 
> # for singularity
> singularity pull docker://quay.io/pacbio/bcftools:1.14_build2
> ```

Thanks for your support. I just want to install and run WDL using cromwell.  I will try use quay.io

**Comment by williamrowell** [comment]
We don't use `latest` tags for these docker images, so pulling an image without specifying a tag will fail.  The WDL workflows pull specific images by the sha256sum of the image.

Please reach out to PacBio Field Support or Tech Support (support@pacb.com) if you have questions about running the workflow.
